[package]
name = "fairmoney"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = "0.5.3"
axum = "0.8.4"
dotenvy = "0.15.7"
headers = "0.4.1"
jsonwebtoken = "9.3.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
sqlx = { version = "0.8.6", features = ["runtime-tokio"] }
thiserror = "2.0.12"
tokio = { version = "1.46.1", features = ["full"] }
tower-http = "0.6.6"
uuid = "1.17.0"
